export enum MeasurandEnumType {
    CurrentExport = "Current.Export",
    CurrentImport = "Current.Import",
    CurrentOffered = "Current.Offered",
    EnergyActiveExportRegister = "Energy.Active.Export.Register",
    EnergyActiveImportRegister = "Energy.Active.Import.Register",
    EnergyReactiveExportRegister = "Energy.Reactive.Export.Register",
    EnergyReactiveImportRegister = "Energy.Reactive.Import.Register",
    EnergyActiveExportInterval = "Energy.Active.Export.Interval",
    EnergyActiveImportInterval = "Energy.Active.Import.Interval",
    EnergyActiveNet = "Energy.Active.Net",
    EnergyReactiveExportInterval = "Energy.Reactive.Export.Interval",
    EnergyReactiveImportInterval = "Energy.Reactive.Import.Interval",
    EnergyReactiveNet = "Energy.Reactive.Net",
    EnergyApparentNet = "Energy.Apparent.Net",
    EnergyApparentImport = "Energy.Apparent.Import",
    EnergyApparentExport = "Energy.Apparent.Export",
    Frequency = "Frequency",
    PowerActiveExport = "Power.Active.Export",
    PowerActiveImport = "Power.Active.Import",
    PowerFactor = "Power.Factor",
    PowerOffered = "Power.Offered",
    PowerReactiveExport = "Power.Reactive.Export",
    PowerReactiveImport = "Power.Reactive.Import",
    SoC = "SoC",
    Voltage = "Voltage"
  }