// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoltaXApi.Data;

#nullable disable

namespace VoltaXApi.Migrations
{
    [DbContext(typeof(VoltaXApiDbContext))]
    partial class VoltaXApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VoltaXApi.Automobile", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photos")
                        .HasColumnType("longtext");

                    b.Property<string>("PressRelease")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Automobiles");
                });

            modelBuilder.Entity("VoltaXApi.Models.Administrator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("VoltaXApi.Models.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("VoltaXApi.Models.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.Property<bool?>("Blocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CardType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePoint", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ChargePointModelID")
                        .HasColumnType("int");

                    b.Property<int?>("ChargingStationID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ClientCertThumb")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("longtext");

                    b.Property<bool?>("HasChargeCable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Make")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<bool?>("ShowOnMap")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.Property<string>("VendorName")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointId")
                        .IsUnique();

                    b.HasIndex("ChargePointModelID");

                    b.HasIndex("ChargingStationID");

                    b.ToTable("ChargePoints");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointBrand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("ChargePointBrands");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointConfigurationItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VariableInstance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("VariableMaxLimit")
                        .HasColumnType("double");

                    b.Property<double?>("VariableMinLimit")
                        .HasColumnType("double");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VariableUnit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VariableValuesList")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("ChargePointConfigurationItems");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointFeatures", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("AutoCharge")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AutoSchedules")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ChargePointModelID")
                        .HasColumnType("int");

                    b.Property<bool?>("FirmwareManagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("LoadBalancing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LocalAuthListManagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Powerbank")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("ReleaseDetection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SolarCharge")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointModelID")
                        .IsUnique();

                    b.ToTable("ChargePointFeaturess");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointIntegration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChargePointModelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Method")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointModelID");

                    b.ToTable("ChargePointIntegrations");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ChargePointBrandID")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointBrandID");

                    b.ToTable("ChargePointModels");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointUptime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChargePointID")
                        .HasColumnType("int");

                    b.Property<string>("ChargePointUptimeStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("ChargePointUptimes");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargeTag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Blocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CardID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("ParentTagId")
                        .HasColumnType("longtext");

                    b.Property<string>("TagID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TagName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CardID");

                    b.HasIndex("TagID")
                        .IsUnique();

                    b.ToTable("ChargeTags");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargingSession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CardID")
                        .HasColumnType("int");

                    b.Property<int>("ChargingSessionStatus")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StoppedReason")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CardID");

                    b.HasIndex("ConnectorID");

                    b.HasIndex("UserID");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargingStation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ChargerQuantity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Network")
                        .HasColumnType("int");

                    b.Property<string>("Organisation")
                        .HasColumnType("longtext");

                    b.Property<bool>("ParkingAmenity")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParkingType")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerID")
                        .HasColumnType("int");

                    b.Property<bool>("RestaurantsAmenity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SittingAreaAmenity")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("WashroomAmenity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WifiAmenity")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PartnerID");

                    b.ToTable("ChargingStations");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargingStationImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChargingStationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ChargingStationID");

                    b.HasIndex("ImageID");

                    b.ToTable("ChargingStationImages");
                });

            modelBuilder.Entity("VoltaXApi.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Flag")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("StateCode")
                        .HasColumnType("longtext");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.HasIndex("StateID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("VoltaXApi.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ChargePointID")
                        .HasColumnType("int");

                    b.Property<int?>("ChargingStationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointID");

                    b.HasIndex("ChargingStationID");

                    b.HasIndex("ConnectorID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("VoltaXApi.Models.CommentImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CommentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<int>("ImagePriority")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CommentID");

                    b.HasIndex("ImageID");

                    b.ToTable("CommentImages");
                });

            modelBuilder.Entity("VoltaXApi.Models.CommentReply", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CommentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Reply")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CommentID");

                    b.ToTable("CommentReplies");
                });

            modelBuilder.Entity("VoltaXApi.Models.ConfigurationItemVariableAttribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChargePointConfigurationItemID")
                        .HasColumnType("int");

                    b.Property<bool?>("Constant")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<int?>("Mutability")
                        .HasColumnType("int");

                    b.Property<bool?>("Persistent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointConfigurationItemID");

                    b.ToTable("ConfigurationItemVariableAttributes");
                });

            modelBuilder.Entity("VoltaXApi.Models.Connector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ChargePointID")
                        .HasColumnType("int");

                    b.Property<int?>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<string>("ConnectorType")
                        .HasColumnType("longtext");

                    b.Property<decimal>("CostPerKwh")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("EvseID")
                        .HasColumnType("int");

                    b.Property<decimal>("FlatFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MaxPower")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PricePerIdleMinute")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PricePerKWh")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double?>("Speed")
                        .HasColumnType("double");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointID");

                    b.HasIndex("EvseID", "ConnectorID", "ChargePointID")
                        .IsUnique();

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("VoltaXApi.Models.ConnectorStatus", b =>
                {
                    b.Property<int?>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<string>("ChargePointID")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ChargePointID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int?>("LastStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastStatusTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ConnectorID", "ChargePointID");

                    b.HasIndex("ChargePointID1");

                    b.ToTable("ConnectorStatuses");
                });

            modelBuilder.Entity("VoltaXApi.Models.ConnectorUptime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<string>("ConnectorUptimeStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TransactionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("TransactionID");

                    b.ToTable("ConnectorUptimes");
                });

            modelBuilder.Entity("VoltaXApi.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Capital")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("longtext");

                    b.Property<string>("Emoji")
                        .HasColumnType("longtext");

                    b.Property<string>("EmojiU")
                        .HasColumnType("longtext");

                    b.Property<bool>("Flag")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Iso2")
                        .HasColumnType("longtext");

                    b.Property<string>("Iso3")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Native")
                        .HasColumnType("longtext");

                    b.Property<string>("NumericCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Phonecode")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("Subregion")
                        .HasColumnType("longtext");

                    b.Property<string>("Timezones")
                        .HasColumnType("longtext");

                    b.Property<string>("Tld")
                        .HasColumnType("longtext");

                    b.Property<string>("Translations")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("VoltaXApi.Models.DebitCard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("DebitCards");
                });

            modelBuilder.Entity("VoltaXApi.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AltText")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Format")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("VoltaXApi.Models.LoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("VoltaXApi.Models.MessageLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ChargePointId")
                        .HasColumnType("longtext");

                    b.Property<int?>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("ContentReceived")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentSent")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("MessageLogs");
                });

            modelBuilder.Entity("VoltaXApi.Models.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("longtext");

                    b.Property<string>("ActionOn")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int?>("NotificationTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("Read")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int?>("SenderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Urgent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("NotificationTypeID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("VoltaXApi.Models.NotificationSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Email")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int?>("NotificationTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Urgent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NotificationTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("VoltaXApi.Models.NotificationType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ForAdmins")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ForCustomers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ForPartners")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("NotificationTypes");
                });

            modelBuilder.Entity("VoltaXApi.Models.OcppComponent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("OcppComponents");
                });

            modelBuilder.Entity("VoltaXApi.Models.OcppVariable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("OcppVariables");
                });

            modelBuilder.Entity("VoltaXApi.Models.OcppVariableComponent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataType")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Instance")
                        .HasColumnType("longtext");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext");

                    b.Property<string>("Variable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("OcppVariableComponents");
                });

            modelBuilder.Entity("VoltaXApi.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int?>("CardID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("RechargeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CardID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VoltaXApi.Models.Partner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email2")
                        .HasColumnType("longtext");

                    b.Property<string>("Email3")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone2")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone3")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("VoltaXApi.Models.Rating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("VoltaXApi.Models.RatingReport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RatingID")
                        .HasColumnType("int");

                    b.Property<int>("ReportCategory")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RatingID");

                    b.HasIndex("UserID");

                    b.ToTable("RatingReports");
                });

            modelBuilder.Entity("VoltaXApi.Models.Report", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ChargePointID")
                        .HasColumnType("int");

                    b.Property<int?>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReportCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointID");

                    b.HasIndex("ConnectorID");

                    b.HasIndex("UserID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("VoltaXApi.Models.ReportImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<int>("ImagePriority")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ImageID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportImages");
                });

            modelBuilder.Entity("VoltaXApi.Models.ReportReply", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Reply")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportReplies");
                });

            modelBuilder.Entity("VoltaXApi.Models.State", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FipsCode")
                        .HasColumnType("longtext");

                    b.Property<bool>("Flag")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Iso2")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("States");
                });

            modelBuilder.Entity("VoltaXApi.Models.SupportedKwh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChargePointModelID")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointModelID");

                    b.ToTable("SupportedKwhs");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedID")
                        .HasColumnType("int");

                    b.Property<int?>("CardID")
                        .HasColumnType("int");

                    b.Property<int?>("ChargePointID")
                        .HasColumnType("int");

                    b.Property<int?>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Criticality")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNotification")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReportCategory")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedByID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AssignedID");

                    b.HasIndex("CardID");

                    b.HasIndex("ChargePointID");

                    b.HasIndex("ConnectorID");

                    b.HasIndex("ResolvedByID");

                    b.HasIndex("UserID");

                    b.ToTable("SystemReports");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReportComment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SystemReportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SystemReportID");

                    b.HasIndex("UserID");

                    b.ToTable("SystemReportComments");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReportCommentImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<int>("SystemReportCommentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ImageID");

                    b.HasIndex("SystemReportCommentID");

                    b.ToTable("SystemReportCommentImage");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReportImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<int>("SystemReportID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ImageID");

                    b.HasIndex("SystemReportID");

                    b.ToTable("SystemReportImage");
                });

            modelBuilder.Entity("VoltaXApi.Models.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int?>("ChargePointID")
                        .HasColumnType("int");

                    b.Property<int>("ChargingSessionID")
                        .HasColumnType("int");

                    b.Property<int?>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<double>("MeterStart")
                        .HasColumnType("double");

                    b.Property<double?>("MeterStop")
                        .HasColumnType("double");

                    b.Property<int?>("StartCardID")
                        .HasColumnType("int");

                    b.Property<string>("StartResult")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("StopCardID")
                        .HasColumnType("int");

                    b.Property<string>("StopReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Uid")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ChargePointID");

                    b.HasIndex("ChargingSessionID");

                    b.HasIndex("ConnectorID");

                    b.HasIndex("StartCardID");

                    b.HasIndex("StopCardID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("VoltaXApi.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Car")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PartnerID")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneVerificationToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("SuspendedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("PartnerID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VoltaXApi.Models.Administrator", b =>
                {
                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.Card", b =>
                {
                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePoint", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePointModel", "ChargePointModel")
                        .WithMany()
                        .HasForeignKey("ChargePointModelID");

                    b.HasOne("VoltaXApi.Models.ChargingStation", "ChargingStation")
                        .WithMany("ChargePoints")
                        .HasForeignKey("ChargingStationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePointModel");

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointFeatures", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePointModel", "Model")
                        .WithOne("Features")
                        .HasForeignKey("VoltaXApi.Models.ChargePointFeatures", "ChargePointModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointIntegration", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePointModel", "Model")
                        .WithMany("Integrations")
                        .HasForeignKey("ChargePointModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointModel", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePointBrand", "ChargePointBrand")
                        .WithMany("Models")
                        .HasForeignKey("ChargePointBrandID");

                    b.Navigation("ChargePointBrand");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargeTag", b =>
                {
                    b.HasOne("VoltaXApi.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardID");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargingSession", b =>
                {
                    b.HasOne("VoltaXApi.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Connector");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargingStation", b =>
                {
                    b.HasOne("VoltaXApi.Models.Partner", "Partner")
                        .WithMany("ChargingStations")
                        .HasForeignKey("PartnerID");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargingStationImage", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargingStation", "ChargingStation")
                        .WithMany("ChargingStationImages")
                        .HasForeignKey("ChargingStationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("VoltaXApi.Models.City", b =>
                {
                    b.HasOne("VoltaXApi.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID");

                    b.HasOne("VoltaXApi.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateID");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("VoltaXApi.Models.Comment", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePoint", "ChargePoint")
                        .WithMany()
                        .HasForeignKey("ChargePointID");

                    b.HasOne("VoltaXApi.Models.ChargingStation", "ChargingStation")
                        .WithMany()
                        .HasForeignKey("ChargingStationID");

                    b.HasOne("VoltaXApi.Models.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorID");

                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("ChargePoint");

                    b.Navigation("ChargingStation");

                    b.Navigation("Connector");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.CommentImage", b =>
                {
                    b.HasOne("VoltaXApi.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("VoltaXApi.Models.CommentReply", b =>
                {
                    b.HasOne("VoltaXApi.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("VoltaXApi.Models.ConfigurationItemVariableAttribute", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePointConfigurationItem", "ChargePointConfigurationItem")
                        .WithMany("VariableAttributes")
                        .HasForeignKey("ChargePointConfigurationItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePointConfigurationItem");
                });

            modelBuilder.Entity("VoltaXApi.Models.Connector", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePoint", "ChargePoint")
                        .WithMany("Connectors")
                        .HasForeignKey("ChargePointID");

                    b.Navigation("ChargePoint");
                });

            modelBuilder.Entity("VoltaXApi.Models.ConnectorStatus", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePoint", "ChargePoint")
                        .WithMany()
                        .HasForeignKey("ChargePointID1");

                    b.HasOne("VoltaXApi.Models.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePoint");

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("VoltaXApi.Models.ConnectorUptime", b =>
                {
                    b.HasOne("VoltaXApi.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionID");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("VoltaXApi.Models.DebitCard", b =>
                {
                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany("DebitCards")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.Notification", b =>
                {
                    b.HasOne("VoltaXApi.Models.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeID");

                    b.HasOne("VoltaXApi.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID");

                    b.HasOne("VoltaXApi.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID");

                    b.Navigation("NotificationType");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VoltaXApi.Models.NotificationSetting", b =>
                {
                    b.HasOne("VoltaXApi.Models.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeID");

                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.Order", b =>
                {
                    b.HasOne("VoltaXApi.Models.Card", "Card")
                        .WithMany("Orders")
                        .HasForeignKey("CardID");

                    b.HasOne("VoltaXApi.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserID");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("VoltaXApi.Models.Rating", b =>
                {
                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.RatingReport", b =>
                {
                    b.HasOne("VoltaXApi.Models.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingID");

                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.Report", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePoint", "ChargePoint")
                        .WithMany()
                        .HasForeignKey("ChargePointID");

                    b.HasOne("VoltaXApi.Models.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorID");

                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePoint");

                    b.Navigation("Connector");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.ReportImage", b =>
                {
                    b.HasOne("VoltaXApi.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("VoltaXApi.Models.ReportReply", b =>
                {
                    b.HasOne("VoltaXApi.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("VoltaXApi.Models.State", b =>
                {
                    b.HasOne("VoltaXApi.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryID");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("VoltaXApi.Models.SupportedKwh", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePointModel", "ChargePointModel")
                        .WithMany("SupportedKwhs")
                        .HasForeignKey("ChargePointModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePointModel");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReport", b =>
                {
                    b.HasOne("VoltaXApi.Models.User", "Assigned")
                        .WithMany()
                        .HasForeignKey("AssignedID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VoltaXApi.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardID");

                    b.HasOne("VoltaXApi.Models.ChargePoint", "ChargePoint")
                        .WithMany()
                        .HasForeignKey("ChargePointID");

                    b.HasOne("VoltaXApi.Models.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorID");

                    b.HasOne("VoltaXApi.Models.User", "Resolved")
                        .WithMany()
                        .HasForeignKey("ResolvedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Assigned");

                    b.Navigation("Card");

                    b.Navigation("ChargePoint");

                    b.Navigation("Connector");

                    b.Navigation("Resolved");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReportComment", b =>
                {
                    b.HasOne("VoltaXApi.Models.SystemReport", "SystemReport")
                        .WithMany()
                        .HasForeignKey("SystemReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemReport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReportCommentImage", b =>
                {
                    b.HasOne("VoltaXApi.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.SystemReportComment", "SystemReportComment")
                        .WithMany("SystemReportCommentImages")
                        .HasForeignKey("SystemReportCommentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("SystemReportComment");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReportImage", b =>
                {
                    b.HasOne("VoltaXApi.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.SystemReport", "SystemReport")
                        .WithMany("Images")
                        .HasForeignKey("SystemReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("SystemReport");
                });

            modelBuilder.Entity("VoltaXApi.Models.Transaction", b =>
                {
                    b.HasOne("VoltaXApi.Models.ChargePoint", null)
                        .WithMany("Transactions")
                        .HasForeignKey("ChargePointID");

                    b.HasOne("VoltaXApi.Models.ChargingSession", "ChargingSession")
                        .WithMany("Transactions")
                        .HasForeignKey("ChargingSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoltaXApi.Models.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorID");

                    b.HasOne("VoltaXApi.Models.Card", "StartCard")
                        .WithMany()
                        .HasForeignKey("StartCardID");

                    b.HasOne("VoltaXApi.Models.Card", "StopCard")
                        .WithMany()
                        .HasForeignKey("StopCardID");

                    b.Navigation("ChargingSession");

                    b.Navigation("Connector");

                    b.Navigation("StartCard");

                    b.Navigation("StopCard");
                });

            modelBuilder.Entity("VoltaXApi.Models.User", b =>
                {
                    b.HasOne("VoltaXApi.Models.Partner", "Partner")
                        .WithMany("Users")
                        .HasForeignKey("PartnerID");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("VoltaXApi.Models.Card", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePoint", b =>
                {
                    b.Navigation("Connectors");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointBrand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointConfigurationItem", b =>
                {
                    b.Navigation("VariableAttributes");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargePointModel", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Integrations");

                    b.Navigation("SupportedKwhs");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargingSession", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("VoltaXApi.Models.ChargingStation", b =>
                {
                    b.Navigation("ChargePoints");

                    b.Navigation("ChargingStationImages");
                });

            modelBuilder.Entity("VoltaXApi.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("VoltaXApi.Models.Partner", b =>
                {
                    b.Navigation("ChargingStations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("VoltaXApi.Models.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReport", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("VoltaXApi.Models.SystemReportComment", b =>
                {
                    b.Navigation("SystemReportCommentImages");
                });

            modelBuilder.Entity("VoltaXApi.Models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("DebitCards");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
